# Generated by Django 3.0.4 on 2020-06-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200624_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
