# Generated by Django 3.0.4 on 2020-08-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_namestack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameStack',
        ),
    ]
